# Generated by Django 2.0.3 on 2018-04-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180428_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note_db_renote',
            old_name='Tr_group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='note_db_renote',
            old_name='Tr_hashtag',
            new_name='hashtag',
        ),
        migrations.RemoveField(
            model_name='note_db_renote',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='note_db_renote',
            name='count',
        ),
        migrations.RemoveField(
            model_name='note_db_renote',
            name='description',
        ),
        migrations.RemoveField(
            model_name='note_db_renote',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='note_db_renote',
            name='note',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
