# Generated by Django 2.0.3 on 2018-04-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180428_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Note_Db_Renote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Users_Db_Renote')),
            ],
        ),
    ]
