# Generated by Django 2.0.3 on 2018-05-03 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180428_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='users_db_renote',
            name='private',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='follow_db',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='api.Users_Db_Renote'),
        ),
        migrations.AddField(
            model_name='follow_db',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='api.Users_Db_Renote'),
        ),
    ]
