# Generated by Django 2.0.3 on 2018-05-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180504_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow_db',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
